# CI/CD pipeline for Membership Initiation System (Frontend)
# General best-practice config for Node.js + Cypress + build + deploy

name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  install-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true

      - name: Run unit tests
        run: npm run test:unit -- --ci --coverage

      - name: Run E2E tests (Cypress)
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:5173"
          wait-on-timeout: 60
          command: npm run test:e2e

      - name: Build
        run: npm run build

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  deploy:
    needs: install-build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # Add your deployment step here (e.g., upload to S3, Vercel, Netlify, etc.)
      - name: Deploy (placeholder)
        run: echo "Deploy step goes here."
      - name: Notify on success
        run: echo "Deployment successful!"
